services:
  ui:
    container_name: ui
    build:
      context: ./ui
    ports:
      - "3000:3000"
    volumes: [ ./ui:/app ]
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes: [ ./backend:/app ]
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    healthcheck:
      test: curl --fail -s http://localhost:5000/healthcheck | grep 'Healthy!' || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    # for pdb
    stdin_open: true
    tty: true
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
    - 80:80
    links:
      - ui
      - backend
