name: Doro Traffic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test_ui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./ui --tag doro-traffic-ui:$(date +%s)


  test_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./ui --tag doro-traffic-backend:$(date +%s)

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test